apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quangpv-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - blog.quangpv.tech
    secretName: quangpv-tech-tls
  rules:
  - host: blog.quangpv.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quangpv-service
            port:
              number: 80
