apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanlv-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - tanlv.io.vn
    secretName: tls-tanlv-io-vn
  ingressClassName: nginx
  rules:
  - host: tanlv.io.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tanlv-web-svc
            port:
              number: 80
