apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-tanlv-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - network.tanlv.io.vn
    secretName: tls-network-tanlv-io-vn
  ingressClassName: nginx
  rules:
  - host: network.tanlv.io.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: network-tanlv-web-svc
            port:
              number: 80
